# Open any file with a fragment in vim, fragments are generated
# by the hyperlink-grep kitten and nothing else so far.
# protocol file
# fragment_matches [0-9]+
# action launch --type=overlay --cwd=current nvim +${FRAGMENT} -- ${FILE_PATH}
#
# # Open text files without fragments in the editor
# protocol file
# mime text/*
# action launch --type=overlay --cwd=current -- ${EDITOR} -- ${FILE_PATH}

# change to clicked directory and automatically eza
protocol file
mime inode/directory
action send_text all cd "${FILE_PATH}"; and eza\r

# # show clicked picture inline as if you did an icat in the terminal
# protocol file
# mime image/*
# action send_text normal,application kitty +kitten icat "${FILE_PATH}"\r
