hl.env("HYPRCURSOR_THEME", "Bibata-Modern-Green-Mocha")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("QT_QPA_PLATFORMTHEME", "kde")
-- hl.env("AQ_NO_MODIFIERS", "1")
-- hl.env("AQ_FORCE_LINEAR_BLIT", "0")
hl.env("XDG_DESKTOP_DIR", "$HOME/Archive/Desktop")
hl.env("XDG_DOWNLOAD_DIR", "$HOME/Archive/Downloads")
hl.env("XDG_TEMPLATES_DIR", "$HOME/Archive/Templates")
hl.env("XDG_PUBLICSHARE_DIR", "$HOME/Archive/Public")
hl.env("XDG_DOCUMENTS_DIR", "$HOME/Archive/Documents")
hl.env("XDG_MUSIC_DIR", "$HOME/Archive/Music")
hl.env("XDG_PICTURES_DIR", "$HOME/Archive/Pictures")
hl.env("XDG_VIDEOS_DIR", "$HOME/Archive/Videos")
