splash = false

wallpaper {
    monitor = desc:Chimei Innolux Corporation 0x15E0
    path = ~/Archive/Pictures/wallcrop/snowyBranches/eDP-1.png
    fit_mode = cover
}
wallpaper {
    monitor = desc:Samsung Electric Company SAMSUNG 0x00000001
    path = ~/Archive/Pictures/wallcrop/snowyBranches/DP-2.png
    fit_mode = cover
}
wallpaper {
    monitor = 
    path = ~/Archive/Pictures/wallcrop/snowyBranches.jpg
    fit_mode = cover
}
